"""GENERATED by openapi2mcp. HTTP proxy that fires the real API call."""
import json
import os

import httpx

API_BASE_URL = os.environ.get("API_BASE_URL", "http://localhost:8000").rstrip("/")
API_KEY = os.environ.get("API_KEY")
AUTH_HEADER = os.environ.get("AUTH_HEADER", "Authorization")


def _client():
    return httpx.AsyncClient(timeout=30.0)


async def execute(tool, arguments):
    arguments = dict(arguments or {})
    path = tool["path"]
    for name in tool["path_params"]:
        if name not in arguments:
            return json.dumps({"error": "missing required path parameter: " + name})
        path = path.replace("{" + name + "}", str(arguments.pop(name)))

    params = {}
    for name in tool["query_params"]:
        if name in arguments:
            params[name] = arguments.pop(name)

    json_body = None
    if tool["has_body"]:
        if tool["body_raw"]:
            json_body = arguments.pop("body", None)
        else:
            json_body = {k: arguments[k] for k in tool["body_keys"] if k in arguments}

    headers = {}
    if API_KEY:
        headers[AUTH_HEADER] = API_KEY

    try:
        async with _client() as client:
            resp = await client.request(
                tool["method"].upper(), API_BASE_URL + path,
                params=params or None, json=json_body, headers=headers or None,
            )
    except httpx.HTTPError as exc:
        return json.dumps({"error": "request failed: " + str(exc)})
    try:
        payload = resp.json()
    except Exception:
        payload = resp.text
    return json.dumps({"status": resp.status_code, "body": payload}, default=str)
