"""GENERATED by openapi2mcp. MCP server entrypoint (stdio or Streamable HTTP)."""
import argparse
import asyncio
import contextlib
import json

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

from tools import TOOLS
from executor import execute

server = Server("petstore")
_BY_NAME = {t["name"]: t for t in TOOLS}


@server.list_tools()
async def list_tools():
    return [Tool(name=t["name"], description=t["description"], inputSchema=t["input_schema"]) for t in TOOLS]


@server.call_tool()
async def call_tool(name, arguments):
    tool = _BY_NAME.get(name)
    if tool is None:
        return [TextContent(type="text", text=json.dumps({"error": "unknown tool: " + name}))]
    result = await execute(tool, arguments)
    return [TextContent(type="text", text=result)]


async def _run_stdio():
    async with stdio_server() as (read, write):
        await server.run(read, write, server.create_initialization_options())


def _run_http(host, port):
    """Serve over the Streamable HTTP transport at POST/GET /mcp."""
    import uvicorn
    from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
    from starlette.applications import Starlette
    from starlette.routing import Mount

    session_manager = StreamableHTTPSessionManager(app=server)

    async def handle_mcp(scope, receive, send):
        await session_manager.handle_request(scope, receive, send)

    @contextlib.asynccontextmanager
    async def lifespan(app):
        async with session_manager.run():
            yield

    app = Starlette(routes=[Mount("/mcp", app=handle_mcp)], lifespan=lifespan)
    uvicorn.run(app, host=host, port=port)


def main():
    parser = argparse.ArgumentParser(description="Run the petstore MCP server.")
    parser.add_argument("--transport", choices=["stdio", "http"], default="stdio",
                        help="Transport to serve over (default: stdio).")
    parser.add_argument("--host", default="127.0.0.1",
                        help="Host to bind for --transport http (default: 127.0.0.1).")
    parser.add_argument("--port", type=int, default=8765,
                        help="Port to bind for --transport http (default: 8765).")
    args = parser.parse_args()
    if args.transport == "http":
        _run_http(args.host, args.port)
    else:
        asyncio.run(_run_stdio())


if __name__ == "__main__":
    main()
